In [74]:
# Input.
plaintext ="aminul islam rafi"

# key.
key = [4,1,3,2,0]

In [75]:
# Finding row and col for matrix and adding bogus letter.

col = len(key)

while len(plaintext) % col != 0:
    plaintext += "z"

row = len(plaintext) // col

In [76]:
# Generating key matrix.

k = 0
keyMatrix = np.zeros((col,col),dtype = int)

for j in range(col):
    i = key[k]
    keyMatrix[i][j] = 1
    k += 1
print(keyMatrix)     

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]]


In [77]:
# Encryption.
k=0
ciphertext = ""
plainMatrix = np.zeros((row,col),dtype = int)

for i in range(row):
    for j in range(col):
        plainMatrix[i][j] = ord(plaintext[k]) - 97
        k += 1
print(plainMatrix)
result = np.matmul(plainMatrix,keyMatrix)

for i in range(row):
    for j in range(col):
        ciphertext += chr(result[i][j]+65)

print(result)
print("The corresponding ciphertext is :",ciphertext)

[[  0  12   8  13  20]
 [ 11 -65   8  18  11]
 [  0  12 -65  17   0]
 [  5   8  25  25  25]]
[[ 20  12  13   8   0]
 [ 11 -65  18   8  11]
 [  0  12  17 -65   0]
 [ 25   8  25  25   5]]
The corresponding ciphertext is : UMNIALSILAMRAZIZZF


In [80]:
# Decryption.
k = 0
plaintext =""
cipherMatrix = np.zeros((row,col),dtype=int)

for i in range(row):
    for j in range(col):
        cipherMatrix[i][j] = ord(ciphertext[k]) - 65
        k += 1

inverseKey = np.transpose(keyMatrix)

result = np.matmul(cipherMatrix,inverseKey)

for i in range(row):
    for j in range(col):
        plaintext += chr(result[i][j]+97)
        
print("The corresponding plaintext is :",plaintext)

The corresponding plaintext is : aminul islam rafizzz
